Sonchau/UUID with fk
CanDIG/katsu pull request #158
Opened 2023-11-23 04:11 UTC by SonQBChau

2023-11-27 18:46 UTC, mshadbolt commented
@SonQBChau are you able to add a line to the summary at the top that explains the change to the different package (including the package name) and how it might affect others - change from yaml to json schema

2023-11-27 18:46 UTC, SonQBChau commented
I found a new bug with authorization in docker, temporary take it down

2023-11-27 18:59 UTC, daisieh commented on .github/workflows/update-schema.yaml
> +          npx widdershins ./chord_metadata_service/mohpackets/docs/schema.json -o ./chord_metadata_service/mohpackets/docs/openapi.md -u ./chord_metadata_service/mohpackets/docs/widdershins/templates
Could you add a step to do something like https://stackoverflow.com/questions/38781929/how-to-convert-json-to-yaml-in-javascript, to minimize downstream changes?

2023-11-27 22:13 UTC, SonQBChau commented
> @SonQBChau are you able to add a line to the summary at the top that explains the change to the different package (including the package name) and how it might affect others - change from yaml to json schema, thank you!

I added the packages change

2023-11-29 04:04 UTC, daisieh requested changes
NestedFollowUpSchema does not have any properties in the schema.yml file.

There are still some typos being generated into the schema.yml/json files:
- primarydiagnosis instead of primary_diagnoses
- hormonetherapies instead of hormone_therapies
- samplesregistrations instead of sample_registrations
I think these are misnamed as properties of their parent NestedWhatever objects?

2023-11-29 04:38 UTC, SonQBChau commented
- NestedFollowUpSchema is just a typo, I put Schema instead of ModelSchema so it didn't show up.
- The schema is not being updated is a little complicated. This is a bug through github action. The new schema is generated, but it is not committed yet. However, the commit script can only read the old schema on github repo to get the SHA(which is a requirement to update), which is why the newly generated content is lost. I have to think about it.

2023-11-30 19:54 UTC, daisieh approved these changes
As far as I can tell, this works as expected. Looks good!

2023-12-04 17:45 UTC, OrdiNeu approved these changes
From the data-portal side everything looks fine as far as I can tell, will need some modifications to data portal code to get it working with this but nothing too out-of-the-ordinary :heavy_check_mark: .

2023-12-04 18:33 UTC, merged