Manually update katsu's OpenAPI spec to v3.0 data model
CanDIG/katsu pull request #239
Opened 2024-07-02 19:07 UTC by OrdiNeu

# Description
This implements the CanDIGv3 data model changes as outlined in [this document](https://docs.google.com/document/d/12GACkvTxKc0KhmV3bS8BIySu0qwPBfPzaKqp8NrXaaU/edit).

The updated schema can be found at [chord_metadata_service/mohpackets/docs/schema_manual.yml](https://github.com/CanDIG/katsu/compare/develop...CanDIG:katsu:feature/manual_schema?expand=1#diff-d5342035ee3522f155306050686f455a35a617cb7e7bb1d8560c196b071a90cd)

## Intended list of changes

Changes to the models includes:

Moving a few fields around: 

1. `primary_site` from donor to primary diagnosis, though the endpoints are still able to query based on it
2. `pathological_*`
3. `[“days_per_cycle”, “number_of_cycles”]`, 

Removing a few fields:

1. Surgery's `submitter_specimen_id`
2. Follow-up's `recurrence_*`
3. Treatment's `[“line_of_treatment”, “treatment_setting”]`
4. Primary Diagnosis' `[“lymph_nodes_examined_status”, “lymph_nodes_examined_method”, “number_lymph_nodes_positive”]`

Adding a few fields: 

1. Specimen's `submitter_treatment_id`
2. `[“surgery_reference_database”, “surgery_reference_identifier”]`

And adding the new Systemic Therapy table, which supercedes (and removes) Chemo/Hormonal/Immunotherapy.

This PR does not address how the implementation of the new table, nor the new/changed endpoints, but only outlines what will need to be changed

2024-07-04 00:03 UTC, mshadbolt requested changes
Found a few small things but overall looks really good to me! Thanks!

2024-07-04 00:03 UTC, mshadbolt commented on chord_metadata_service/mohpackets/docs/schema_manual.yml
> +      - Hormone Therapy
Spreadsheet says this should have lowercase on the therapy
```suggestion 
      - Hormone therapy
```

2024-07-04 00:03 UTC, mshadbolt commented on chord_metadata_service/mohpackets/docs/schema_manual.yml
>            - type: integer
This might have been an issue not picked up before but the spreadsheet specifies this as 'number' rather than 'integer' so not sure we can assume non decimal numbers
```suggestion
          - type: number
```

2024-07-04 00:03 UTC, mshadbolt commented on chord_metadata_service/mohpackets/docs/schema_manual.yml
>            - type: integer
Same comment as above
```suggestion
          - type: number
```

2024-07-04 00:03 UTC, mshadbolt commented on chord_metadata_service/mohpackets/docs/schema_manual.yml
>            - type: integer
```suggestion
          - type: number
```

2024-07-04 00:03 UTC, mshadbolt commented on chord_metadata_service/mohpackets/docs/schema_manual.yml
>            - type: integer
```suggestion
          - type: number
```

2024-07-04 00:03 UTC, mshadbolt commented on chord_metadata_service/mohpackets/docs/schema_manual.yml
> +        pathological_m_category:
I think this should be an enum

2024-07-04 00:03 UTC, mshadbolt commented on chord_metadata_service/mohpackets/docs/schema_manual.yml
> +        pathological_n_category:
I think this should have an enum ref

2024-07-04 00:03 UTC, mshadbolt commented on chord_metadata_service/mohpackets/docs/schema_manual.yml
> +        pathological_stage_group:
I think this should have an enum ref

2024-07-04 00:03 UTC, mshadbolt commented on chord_metadata_service/mohpackets/docs/schema_manual.yml
> +        pathological_t_category:
I think this should have an enum ref

2024-07-04 00:03 UTC, mshadbolt commented on chord_metadata_service/mohpackets/docs/schema_manual.yml
> +        pathological_tumour_staging_system:
this should have an enum ref

2024-07-05 00:36 UTC, mshadbolt approved these changes
LGTM

2024-07-05 17:50 UTC, SonQBChau commented
- Line 1044: remove `primary_site` object.
Otherwise, it looks good to me.

2024-07-05 20:16 UTC, kcranston commented
> * Line 1044: remove `primary_site` object.
>   Otherwise, it looks good to me.

Confused about why we are removing `primary_site`. It still exists under Primary Diagnosis in the new model.

2024-07-05 20:19 UTC, OrdiNeu commented
> > * Line 1044: remove `primary_site` object.
> >   Otherwise, it looks good to me.
> 
> Confused about why we are removing `primary_site`. It still exists under Primary Diagnosis in the new model.

It'll be in the DonorWithClinicalData response under the NestedPrimaryDiagnosis schema, so to get the `primate_site` you'd go: `DonorWithClinicalData->primary_diagnoses[i]->primary_site`.

2024-07-05 20:20 UTC, SonQBChau approved these changes

2024-07-05 20:29 UTC, kcranston requested changes
Couple of documentation requests (to help both internal and external folks looking for the updated schema):
* can we change the name of the file to include `v3.0`?
* update the README to point to the new file

2024-07-05 21:18 UTC, kcranston commented
Sorry, that last comment about the readme wasn't clear. I don't think we want to replace all of the instances of `schema` with schema_v3` in the readme until we have updated katsu. I just wanted a line in the readme that mentioned the new, manually created schema for the upcoming model change. I know you are away next week - we can fix this in your absence!

2024-07-08 17:03 UTC, daisieh approved these changes
LGTM

2024-07-08 20:53 UTC, mshadbolt commented on chord_metadata_service/mohpackets/docs/README.MD
> +> Katsu is currently being transitioned to MoH clinical data model v3.0.0. There is a manually created v3.0.0 of the OpenAPI schema at [schema_v3.yml](schema_v3.yml) that can be used as a reference i
@kcranston is this what you were thinking for the line in the README?

2024-07-08 20:53 UTC, kcranston approved these changes

2024-07-08 20:55 UTC, merged