Sonchau/model 3 part 1
CanDIG/katsu pull request #246
Opened 2024-07-30 20:48 UTC by SonQBChau

2024-07-30 21:04 UTC, mshadbolt approved these changes
Overall looks good to me, mostly had a look at the models.

2024-07-31 01:41 UTC, kcranston approved these changes
Reviewing against the model documents, this looks good to me.

2024-07-31 14:35 UTC, OrdiNeu commented
What are the scripts in chord_metadata_service/mohpackets/data/ used for? `data_converter.py` and `data_loader.py` should either be updated or removed

2024-07-31 14:42 UTC, OrdiNeu requested changes

2024-07-31 14:42 UTC, OrdiNeu commented on chord_metadata_service/mohpackets/apis/discovery.py
> +    systemictherapy_drug_names = list(
For readability, should be systemic_therapy
```suggestion
    systemic_therapy_drug_names = list(
```

2024-07-31 14:42 UTC, OrdiNeu commented on chord_metadata_service/mohpackets/apis/discovery.py
> +        "drug_names": systemictherapy_drug_names,
```suggestion
        "drug_names": systemic_therapy_drug_names,
```

2024-07-31 14:42 UTC, OrdiNeu commented on chord_metadata_service/mohpackets/apis/ingestion.py
> +def create_systemictherapies(
If a similar function is `create_primary_diagnoses`, this should follow that convention.
```suggestion
def create_systemic_therapies(
```

2024-07-31 14:42 UTC, OrdiNeu commented on chord_metadata_service/mohpackets/schemas/filter.py
Missing systemic_therapy_type? Feels like the sort of thing we should be able to filter on.

2024-07-31 15:50 UTC, SonQBChau commented
> What are the scripts in chord_metadata_service/mohpackets/data/ used for? `data_converter.py` and `data_loader.py` should either be updated or removed

It will be updated after I merge with Marion's synthetic data

2024-07-31 16:18 UTC, SonQBChau commented
change on systemic_therapy as requested

2024-07-31 19:24 UTC, yavyx requested changes
The treatmentTypeEnum still has the old chemo/hormone/immuno values
[See here](https://github.com/CanDIG/katsu/blob/sonchau/model_3_part_1/chord_metadata_service/mohpackets/docs/schema.yml#L4661)

2024-07-31 19:28 UTC, SonQBChau commented
> The treatmentTypeEnum still has the old chemo/hormone/immuno values [See here](https://github.com/CanDIG/katsu/blob/sonchau/model_3_part_1/chord_metadata_service/mohpackets/docs/schema.yml#L4661)

This change has been addressed in [part 3 ](https://github.com/CanDIG/katsu/pull/248/files#diff-9c4dd410e6ffb078dc81b326de7ed069dbf467816073d1817bcfa92989d79f09L507), so it will be included in the final version

2024-07-31 19:37 UTC, SonQBChau commented
I updated the enum

2024-07-31 20:04 UTC, mshadbolt commented on chord_metadata_service/mohpackets/docs/schema.yml
> +        systemictherapies:
```suggestion
        systemic_therapies:
```
I think it needs an underscore to be consistent with how we have done it for other schemas

2024-08-01 16:30 UTC, OrdiNeu approved these changes

2024-08-01 17:45 UTC, merged